apiVersion: v1
kind: Namespace
metadata:
  name: local-testing-project-chirath-staging
  labels:
    environment-id: env_a3c76b7d-d96a-4680-84ba-c33d7c5914dd
    project-id: project_be9f6dc1-60f5-4a42-9cad-8a7395b11efa
    project-name: local-resource-service-project-chirath
    environment-name: staging
    organization-id: org_d47c88d4-4669-4b20-b366-32ada20b3b70
